version: '3'

services:
  api-gateway:
    build: .
    environment:
      - APP_PORT=${APP_PORT}
      - FLASK_PORT=${FLASK_PORT}
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS}
    image: ypp-api-gateway
    hostname: ypp-api-gateway
    container_name: ypp-api-gateway
    restart: always
    ports:
      - ${APP_PORT}:${FLASK_PORT}
    volumes:
      - ./data/db:/var/sqlite/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    hostname: ypp-es
    container_name: ypp-es
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    hostname: ypp-kibana
    container_name: ypp-kibana
    ports:
      - 127.0.0.1:5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
